BROKEN: Repo() call causes an error
raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /Users/briandk/Developer/transcriptase/<git.repo.base.Repo '/Users/briandk/Developer/transcriptase/.git'>

---

I think the call to Repo is taking the entire string (/Users/briandk/Developer/transcriptase/<git.repo.base.Repo '/Users/briandk/Developer/transcriptase/.git'>) as input and trying to open that?